---
 - name: Add repository key
   apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B"
    state: present

 - name: Add server repository
   apt_repository:
    repo='deb https://osquery-packages.s3.amazonaws.com/xenial xenial main'
    state=present   

 - name: Install osquery
   apt:
    name={{ item }}
    update_cache=yes
    force=yes
   with_items:
    - osquery
   become: yes
 
 - name: Copy osquery config file
   template:
     src=templates/osquery.conf.j2
     dest=/etc/osquery/osquery.conf
     owner=root
     group=root
     mode=0644
   become: yes
   notify:
     - restart osquery

 - name: Copy rsyslog config file
   template:
     src=templates/pci.conf.j2
     dest=/etc/rsyslog.d/pci.conf
     owner=root
     group=root
     mode=0644
   become: yes
   notify:
     - restart osquery

 - name: Remove rsyslog default file 
   file:
     path=/etc/rsyslog.d/50-default.conf
     state=absent
   notify:
     - restart rsyslog

 - name: Enable Osquery Service 
   systemd:
     name=osqueryd.service
     state=restarted
     daemon_reload=yes
     enabled=yes
   become: yes
